### PR TITLE
Make OPTIONS /pods a paid endpoint

### PR DESCRIPTION
**Pull request by wilsonianb**
Allow uploader to determine the host's asset details when requesting a quote

NOTE: This requires the following dependency updates:
https://github.com/coilhq/cog/pull/4
https://github.com/interledgerjs/ilp-fetch/pull/18

### CODE REVIEW

**Comment by wilsonianb** [comment]
I've incorporated the updated ilp-fetch and cog dependencies and cleaned up the selftest commit.
I haven't come up with a way for backwards compatibility (allowing hosts with this change to support uploaders without https://github.com/codius/codius/pull/75). You could argue that hosts shouldn't support cli's whose price calculations will be incorrect if using a different asset than the host.

**Comment by sharafian** [comment]
Could we just make paid OPTIONS /pods into a new endpoint? then the new CLI can call the new endpoint, but the old CLI can still call the old unpaid endpoint

**Comment by wilsonianb** [comment]
Yeah, that should work.
I think I'm just skeptical about supporting clients that are prone to erroneous price calculations. OTOH, is it the case that STREAM would prevent the uploader from paying anything if its specific max price (`sendMax`) is less than the host's `receiveMax`? So there's no risk of losing funds aside from potentially selecting more expensive hosts due to bad price calculations?

**Comment by sharafian** [comment]
Yeah, STREAM wouldn't pay more than the allowed send max

**Comment by wilsonianb** [comment]
It looks like STREAM will still send `sendMax` even if it is less than the host's `receiveMax`.
So the old cli could:
1. get a quote
2. assume the price is not in a different asset
3. incorrectly determine that the quoted price is below the specified max (eg uploader uses XRP, host uses ETH)
4. attempt to upload to the host

This would result in the uploader paying the specified sendMax amount without successfully uploading the pod.
As far as I can tell, codiusd doesn't have a built in way to refund partial payments.

If that's the case, then I'm still leaning towards not supporting the old cli.

**Comment by sharafian** [comment]
ah, I see. Then yeah, I suppose we better release this and tell everyone to upgrade

**Pull request merged**
